steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/secret-repo/deploy-example', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/secret-repo/deploy-example"]

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'deploy-example'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/secret-repo/deploy-example'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
